//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myApplication.GetTip {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetTip.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTip", ReplyAction="http://tempuri.org/IService/GetTipResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tipReturn")]
        string GetTip(double bill, double percentage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTip", ReplyAction="http://tempuri.org/IService/GetTipResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tipReturn")]
        System.Threading.Tasks.Task<string> GetTipAsync(double bill, double percentage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : myApplication.GetTip.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<myApplication.GetTip.IService>, myApplication.GetTip.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTip(double bill, double percentage) {
            return base.Channel.GetTip(bill, percentage);
        }
        
        public System.Threading.Tasks.Task<string> GetTipAsync(double bill, double percentage) {
            return base.Channel.GetTipAsync(bill, percentage);
        }
    }
}
